version: '3.8'

services:
  # Banco de Dados SQL
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha_secreta_root
      MYSQL_DATABASE: centro_academico
      MYSQL_USER: usuario_node
      MYSQL_PASSWORD: senha_node
    volumes:
      # Onde o MariaDB salva os dados (para não perder se reiniciar)
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  # Backend Node.js
  api:
    build: ./api
    ports:
      - "3000:3000"
    volumes:
      - ./uploads_data:/app/public/uploads
    depends_on:
      - db
    environment:
      # String de conexão: usuario:senha@nome_do_servico_docker:porta/nome_banco
      - DB_HOST=db
      - DB_USER=usuario_node
      - DB_PASS=senha_node
      - DB_NAME=centro_academico

  # Frontend (Nginx) - Continua igual
  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./web:/usr/share/nginx/html
      - ./uploads_data:/usr/share/nginx/html/uploads

volumes:
  mariadb_data: